// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Coord, Direction } from "./../../systems/MoveSystem.sol";

interface IMoveSystem {
  function move(Coord memory start, Direction direction) external;
}
