// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Coord } from "./../../systems/SpawnSystem.sol";

interface ISpawnSystem {
  function spawn() external returns (Coord memory);
}
