// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { StateOwnerTable, StateOwnerTableTableId } from "./tables/StateOwnerTable.sol";
import { LastUpdateTable, LastUpdateTableTableId } from "./tables/LastUpdateTable.sol";
import { TroopCountTable, TroopCountTableTableId } from "./tables/TroopCountTable.sol";
import { IsCapitalTable, IsCapitalTableTableId } from "./tables/IsCapitalTable.sol";
import { StateTable, StateTableTableId } from "./tables/StateTable.sol";
import { FoundedTable, FoundedTableTableId } from "./tables/FoundedTable.sol";
import { HomeStateTable, HomeStateTableTableId } from "./tables/HomeStateTable.sol";
